class ShopwebThirdpartyFaceConst():
    open_shopweb_thirdparty_face_registerVip = 'open.shopweb.thirdparty.face.registerVip'
    open_shopweb_thirdparty_face_getFaceCustomer = 'open.shopweb.thirdparty.face.getFaceCustomer'
    open_shopweb_thirdparty_face_queryUserCallBack = 'open.shopweb.thirdparty.face.queryUserCallBack'
    open_shopweb_thirdparty_face_getFaceCustomerList = 'open.shopweb.thirdparty.face.getFaceCustomerList'
    open_shopweb_thirdparty_face_getSnapshotOnDevice = 'open.shopweb.thirdparty.face.getSnapshotOnDevice'
    open_shopweb_thirdparty_face_updateVip = 'open.shopweb.thirdparty.face.updateVip'
    open_shopweb_thirdparty_face_getPosFaceCustomerList = 'open.shopweb.thirdparty.face.getPosFaceCustomerList'
    open_shopweb_thirdparty_face_updateFaceCustomerRemark = 'open.shopweb.thirdparty.face.updateFaceCustomerRemark'
    open_shopweb_thirdparty_face_searchUser = 'open.shopweb.thirdparty.face.searchUser'
    open_shopweb_thirdparty_face_registerVip = 'open.shopweb.thirdparty.face.registerVip'
    open_shopweb_thirdparty_face_getFaceCustomerList = 'open.shopweb.thirdparty.face.getFaceCustomerList'
    open_shopweb_thirdparty_face_getDepCustomerAgeReport = 'open.shopweb.thirdparty.face.getDepCustomerAgeReport'
    open_shopweb_thirdparty_face_getDepCustomerGenderReport = 'open.shopweb.thirdparty.face.getDepCustomerGenderReport'
    open_shopweb_thirdparty_face_getVipList = 'open.shopweb.thirdparty.face.getVipList'
    open_shopweb_thirdparty_face_getBatchFlowData = 'open.shopweb.thirdparty.face.getBatchFlowData'